package api

import (
	"os"
	"os/exec"
	"strings"
	"testing"
)

// flash.sh parses three values out of the seed the Add-node wizard generates:
// the node id, the role, and the NATS URL (which is where the control-plane URL
// is derived from). The wizard's seeds come from proto.RenderSeed, which emits
// SINGLE-QUOTED values -- so a parser that keeps the quotes gets three wrong
// answers and says nothing about it.
//
// That is what shipped. Bench, 2026-09-21, flashing a firewall seed the wizard
// had just produced:
//
//	==> Asking https://'nats which Rasputin OS (amd64) image this cluster runs...
//
// Two failures in one line. NODE_ROLE was 'firewall' WITH quotes, which matches
// no case arm, so the script fell through to the OS-node branch and set out to
// write an OS image onto a firewall. And the NATS host
// parse ran on 'nats://bench.local:4222', where ^[a-z]*:// cannot match a
// leading quote, so it truncated at the first colon to 'nats.
//
// Neither is caught by anything else: the role only reveals itself as the wrong
// image on a disk, and the URL failure is reported as "this laptop isn't on the
// cluster's network", which sends the operator to debug the wrong thing.
//
// This test drives the real seed_val out of the real flash.sh, so it cannot
// drift from what the control plane serves.
func seedValFromFlashScript(t *testing.T, seed, key string) string {
	t.Helper()
	src, err := os.ReadFile("flash.sh")
	if err != nil {
		t.Fatalf("read flash.sh: %v", err)
	}
	start := strings.Index(string(src), "seed_val() {")
	if start < 0 {
		t.Fatal("seed_val() not found in flash.sh -- has it been renamed?")
	}
	end := strings.Index(string(src)[start:], "\n}")
	if end < 0 {
		t.Fatal("seed_val() has no closing brace")
	}
	fn := string(src)[start : start+end+2]

	script := "set -eu\nSEED=\"$1\"\n" + fn + "\nseed_val \"$2\"\n"
	out, err := exec.Command("sh", "-c", script, "sh", seed, key).Output()
	if err != nil {
		t.Fatalf("running seed_val for %s: %v", key, err)
	}
	return strings.TrimRight(string(out), "\n")
}

func TestFlashSeedValStripsOneQuoteLayer(t *testing.T) {
	// Byte-for-byte what the Add-node wizard handed the operator on the bench.
	wizard := "# seed.env — Rasputin node enrollment file, generated by the Rasputin control plane\n" +
		"RASPUTIN_NODE_ROLE='firewall'\n" +
		"RASPUTIN_NODE_ID='cp-firewall1'\n" +
		"RASPUTIN_CLUSTER_ID='bench'\n" +
		"RASPUTIN_NATS_URL='nats://bench.local:4222'\n"

	for _, tc := range []struct{ key, want string }{
		{"RASPUTIN_NODE_ROLE", "firewall"},
		{"RASPUTIN_NODE_ID", "cp-firewall1"},
		{"RASPUTIN_NATS_URL", "nats://bench.local:4222"},
	} {
		if got := seedValFromFlashScript(t, wizard, tc.key); got != tc.want {
			t.Errorf("%s = %q, want %q (a kept quote layer is the 2026-09-21 bench failure)", tc.key, got, tc.want)
		}
	}

	// A quoted NATS URL must still yield a usable control-plane host. This is
	// the value that became https://'nats.
	url := seedValFromFlashScript(t, wizard, "RASPUTIN_NATS_URL")
	host := strings.TrimPrefix(url, "nats://")
	if i := strings.IndexByte(host, ':'); i >= 0 {
		host = host[:i]
	}
	if host != "bench.local" {
		t.Errorf("derived control-plane host = %q, want %q", host, "bench.local")
	}
}

func TestFlashSeedValAcceptsEveryQuotingStyle(t *testing.T) {
	// Unquoted and double-quoted seeds predate RenderSeed and are still valid
	// input -- proto.ParseSeed accepts all three, and so must this.
	for _, tc := range []struct{ name, seed, want string }{
		{"single-quoted (what the wizard emits)", "RASPUTIN_NODE_ROLE='firewall'\n", "firewall"},
		{"double-quoted (legacy seeds)", "RASPUTIN_NODE_ROLE=\"firewall\"\n", "firewall"},
		{"unquoted (hand-written)", "RASPUTIN_NODE_ROLE=firewall\n", "firewall"},
	} {
		if got := seedValFromFlashScript(t, tc.seed, "RASPUTIN_NODE_ROLE"); got != tc.want {
			t.Errorf("%s: got %q, want %q", tc.name, got, tc.want)
		}
	}
}
