package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/geekdojo/rasputin-control-plane/proto"
)

func writeSeed(t *testing.T, contents string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "rasputin-seed.env")
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func seedCheck(t *testing.T, args ...string) (code int, stdout, stderr string) {
	t.Helper()
	var out, errBuf bytes.Buffer
	code, handled := dispatchCLI(append([]string{"seed"}, args...), &out, &errBuf)
	if !handled {
		t.Fatal("dispatchCLI did not handle the seed command")
	}
	return code, out.String(), errBuf.String()
}

func TestSeedCheck_AcceptsAGoodSeedAndNormalizesIt(t *testing.T) {
	rendered, err := proto.RenderSeed(proto.Seed{
		Role: proto.RoleCompute, NodeID: "home1-compute1", ClusterID: "home1",
		NATSURL:          "nats://home1.local:4222",
		JoinToken:        "tok-abc",
		BusPin:           proto.BusPinPrefix + "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
		SSHAuthorizedKey: "ssh-ed25519 AAAA me@laptop",
		Origin:           "the Rasputin control plane",
	})
	if err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr := seedCheck(t, "check", writeSeed(t, rendered))
	if code != 0 {
		t.Fatalf("exit=%d stderr=%s", code, stderr)
	}
	// The output is this binary's own, so it says so — an image sourcing it
	// is sourcing something the agent wrote, not the operator's file.
	if !strings.Contains(stdout, "rasputin-agent seed check") {
		t.Errorf("output does not say what produced it:\n%s", stdout)
	}
	got, err := proto.ParseSeed(strings.NewReader(stdout))
	if err != nil {
		t.Fatalf("the output does not parse: %v\n%s", err, stdout)
	}
	if got.NodeID != "home1-compute1" || got.JoinToken != "tok-abc" || got.SSHAuthorizedKey != "ssh-ed25519 AAAA me@laptop" {
		t.Errorf("fields lost in normalisation: %+v", got)
	}
}

// The older unquoted seeds are still on the FAT volumes of every node that has
// not been reflashed, and this command has to accept them — it is the reader
// changing, not the format.
func TestSeedCheck_AcceptsTheOlderUnquotedSeed(t *testing.T) {
	old := "# rasputin-seed.env — generated by rasputin-provision\n" +
		"RASPUTIN_NODE_ROLE=compute\n" +
		"RASPUTIN_NODE_ID=compute1\n" +
		"RASPUTIN_CLUSTER_ID=home1\n" +
		"RASPUTIN_NATS_URL=nats://home1.local:4222\n" +
		"RASPUTIN_CP_JOIN_TOKEN=tok-abc\n" +
		"RASPUTIN_SSH_AUTHORIZED_KEY=\"ssh-ed25519 AAAA me@laptop\"\n"
	code, stdout, stderr := seedCheck(t, "check", writeSeed(t, old))
	if code != 0 {
		t.Fatalf("exit=%d stderr=%s", code, stderr)
	}
	got, err := proto.ParseSeed(strings.NewReader(stdout))
	if err != nil {
		t.Fatal(err)
	}
	if got.SSHAuthorizedKey != "ssh-ed25519 AAAA me@laptop" {
		t.Errorf("ssh key = %q", got.SSHAuthorizedKey)
	}
}

// Keys this build does not name are carried through, not dropped: both images
// read several (the NTP server, the BMC host, the fallback address), and a
// seed from a newer control plane may carry more.
func TestSeedCheck_CarriesUnknownKeysThrough(t *testing.T) {
	in := "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='n1'\nRASPUTIN_CP_JOIN_TOKEN='t'\n" +
		"RASPUTIN_NTP_SERVER='ntp1.example 10.0.0.1'\nRASPUTIN_FALLBACK_ADDRESS=''\n"
	code, stdout, stderr := seedCheck(t, "check", writeSeed(t, in))
	if code != 0 {
		t.Fatalf("exit=%d stderr=%s", code, stderr)
	}
	got, err := proto.ParseSeed(strings.NewReader(stdout))
	if err != nil {
		t.Fatal(err)
	}
	if got.Extra["RASPUTIN_NTP_SERVER"] != "ntp1.example 10.0.0.1" {
		t.Errorf("the NTP server was lost: %v", got.Extra)
	}
	// Set-but-empty is the operator's explicit "take no fallback address";
	// dropping the line would silently restore the default.
	if _, present := got.Extra["RASPUTIN_FALLBACK_ADDRESS"]; !present {
		t.Errorf("an explicitly empty key was dropped: %v", got.Extra)
	}
}

// Every refusal prints NOTHING on stdout. An image that pipes stdout into a
// file it then sources must get an empty file, never half a seed.
func TestSeedCheck_RefusalsPrintNothingOnStdout(t *testing.T) {
	for _, tc := range []struct {
		name, seed, wantErr string
		args                []string
	}{
		{name: "no role", seed: "RASPUTIN_NODE_ID='n1'\n", wantErr: proto.SeedKeyRole},
		{name: "unknown role", seed: "RASPUTIN_NODE_ROLE='router'\nRASPUTIN_NODE_ID='n1'\n", wantErr: "router"},
		{name: "no node id", seed: "RASPUTIN_NODE_ROLE='compute'\n", wantErr: proto.SeedKeyNodeID},
		{name: "bad node id", seed: "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='Node_1'\n", wantErr: proto.SeedKeyNodeID},
		{name: "no token on a compute node", seed: "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='n1'\n", wantErr: proto.SeedKeyJoinToken},
		{
			name:    "an unusable pin",
			seed:    "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='n1'\nRASPUTIN_CP_JOIN_TOKEN='t'\nRASPUTIN_BUS_PIN='not-a-pin'\n",
			wantErr: proto.SeedKeyBusPin,
		},
		{
			name:    "a line that is not KEY=VALUE",
			seed:    "RASPUTIN_NODE_ROLE='compute'\nrm -rf /\n",
			wantErr: "not KEY=VALUE",
		},
		{
			name:    "a value a shell would expand",
			seed:    "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID=$(id)\n",
			wantErr: "shell",
		},
		{
			name:    "the wrong role for this image",
			seed:    "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='n1'\nRASPUTIN_CP_JOIN_TOKEN='t'\n",
			args:    []string{"--role", "firewall"},
			wantErr: "another node",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			args := append([]string{"check"}, tc.args...)
			code, stdout, stderr := seedCheck(t, append(args, writeSeed(t, tc.seed))...)
			if code != 1 {
				t.Fatalf("exit=%d, want 1\nstdout=%s\nstderr=%s", code, stdout, stderr)
			}
			if stdout != "" {
				t.Errorf("a refusal wrote to stdout:\n%s", stdout)
			}
			if !strings.Contains(stderr, tc.wantErr) {
				t.Errorf("stderr %q does not mention %q", stderr, tc.wantErr)
			}
		})
	}
}

// A controlplane seed legitimately carries no join token: its api mints its
// own agent's at start.
func TestSeedCheck_ControlplaneNeedsNoToken(t *testing.T) {
	in := "RASPUTIN_NODE_ROLE='controlplane'\nRASPUTIN_NODE_ID='cp1'\nRASPUTIN_BUS_AUTH='enforce'\n"
	if code, _, stderr := seedCheck(t, "check", writeSeed(t, in)); code != 0 {
		t.Fatalf("exit=%d stderr=%s", code, stderr)
	}
}

// A node whose image already puts the token in a file names the file instead
// of carrying the token (§7 4.1), and that is not a seed with no credential.
func TestSeedCheck_AcceptsATokenFileInsteadOfAToken(t *testing.T) {
	in := "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='n1'\nRASPUTIN_CP_JOIN_TOKEN_FILE='/var/lib/rasputin/bus/join.token'\n"
	if code, _, stderr := seedCheck(t, "check", writeSeed(t, in)); code != 0 {
		t.Fatalf("exit=%d stderr=%s", code, stderr)
	}
}

// A flag AFTER the path is parsed, not silently dropped. This is how an
// operator types it off a runbook, and it is the exact shape that once left
// verify-artifact's --trust-root unread while the command still exited 0.
func TestSeedCheck_FlagsWorkOnEitherSideOfThePath(t *testing.T) {
	seed := "RASPUTIN_NODE_ROLE='compute'\nRASPUTIN_NODE_ID='n1'\nRASPUTIN_CP_JOIN_TOKEN='t'\n"
	path := writeSeed(t, seed)
	for _, args := range [][]string{
		{"check", "--role", "firewall", path},
		{"check", path, "--role", "firewall"},
	} {
		code, stdout, stderr := seedCheck(t, args...)
		if code != 1 {
			t.Errorf("%v: exit=%d, want 1 (the role check must run)\nstdout=%s", args, code, stdout)
		}
		if !strings.Contains(stderr, "another node") {
			t.Errorf("%v: stderr = %q", args, stderr)
		}
	}
}

func TestSeedCheck_UsageErrors(t *testing.T) {
	for _, args := range [][]string{{}, {"nonsense"}, {"check"}, {"check", "a", "b"}} {
		code, stdout, _ := seedCheck(t, args...)
		if code != 2 {
			t.Errorf("%v: exit=%d, want 2", args, code)
		}
		if stdout != "" {
			t.Errorf("%v: wrote to stdout:\n%s", args, stdout)
		}
	}
	// A missing file is an unusable seed (1), not a usage error.
	if code, _, _ := seedCheck(t, "check", filepath.Join(t.TempDir(), "absent.env")); code != 1 {
		t.Errorf("a missing seed: exit=%d, want 1", code)
	}
}

// THE POINT of the command: an image sources the OUTPUT, and nothing in a
// hostile seed runs when it does.
func TestSeedCheck_OutputIsSafeToSource(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skipf("no sh on this machine: %v", err)
	}
	dir := t.TempDir()
	canary := filepath.Join(dir, "canary")
	// A seed an operator might be handed: every value is quoted, as the
	// control plane renders it, but the CONTENTS are hostile.
	rendered, err := proto.RenderSeed(proto.Seed{
		Role: proto.RoleCompute, NodeID: "n1", ClusterID: "home1",
		JoinToken:        "tok",
		SSHAuthorizedKey: "ssh-ed25519 AAAA $(touch " + canary + ")`touch " + canary + "`; touch " + canary,
	})
	if err != nil {
		t.Fatal(err)
	}
	code, stdout, stderr := seedCheck(t, "check", writeSeed(t, rendered))
	if code != 0 {
		t.Fatalf("exit=%d stderr=%s", code, stderr)
	}
	checked := filepath.Join(dir, "checked.env")
	if err := os.WriteFile(checked, []byte(stdout), 0o600); err != nil {
		t.Fatal(err)
	}
	script := ". '" + checked + "'; printf '<%s>' \"$" + proto.SeedKeySSHKey + "\""
	out, err := exec.Command(sh, "-c", script).Output() // #nosec G204 -- this test's own script and temp dir
	if err != nil {
		t.Fatalf("sourcing the checked seed failed: %v", err)
	}
	if _, err := os.Stat(canary); err == nil {
		t.Fatal("sourcing the checked seed executed a value")
	}
	if !strings.HasPrefix(string(out), "<ssh-ed25519 AAAA $(touch") {
		t.Errorf("the value did not survive as data: %s", out)
	}
}
