// Node-enrollment helpers for the "Add node" flow. The seed renderer mirrors
// buildrootSeed() in cmd/rasputin-provision so a UI-minted node and a
// CLI-provisioned node consume byte-compatible enrollment files — the firstboot
// oneshot parses the same KEY=VALUE lines either way.

// The locked control-plane name. Agents resolve it via mDNS, so the seed never
// carries an IP (avoids the F-LOG-1 churn — see token-provisioning-pipeline.md).
export const DEFAULT_NATS_URL = 'nats://rasputin.local:4222';

// Roles a user can add from the UI. The controlplane self-registers, so it's
// never an "add a node" path. `firewall` IS addable, but on a separate branch:
// it's a distinct, x86-only image that enrolls over SSH (not the flash.sh /
// ESP-seed path the compute/storage OS nodes use) — see renderFirewallSeed +
// firewallApplyCommand.
export type AddableRole = 'compute' | 'storage' | 'firewall';

// Target CPU architecture for a new node's OS image. The node OS is one image
// per arch with the role selected at runtime (via the seed), so arch is
// independent of role — a single arm64 image serves a compute, storage, or
// controlplane node alike. The firewall is a separate, x86-only image on its
// own enrollment branch (renderFirewallSeed) — this arch type covers only the
// OS-node path.
export type NodeArch = 'amd64' | 'arm64';

// Per-arch board SKU + display copy. amd64 → the N100 (Intel) board image;
// arm64 → the `rpi` SKU (one unified image for Raspberry Pi 4 / Pi 5 / CM5).
// The public image asset names and the release manifest's `compatible` string
// both key off the SKU.
export const NODE_ARCHES: { value: NodeArch; sku: string; label: string; blurb: string }[] = [
  { value: 'amd64', sku: 'n100', label: 'AMD64', blurb: 'Intel / AMD x86-64' },
  { value: 'arm64', sku: 'rpi', label: 'ARM64', blurb: 'Raspberry Pi / ARM64' },
];

// skuForArch maps an arch to the board SKU used in image asset names
// (rasputin-os-<sku>-<version>.img.xz). Defaults to the amd64/n100 SKU.
export function skuForArch(arch: NodeArch): string {
  return arch === 'arm64' ? 'rpi' : 'n100';
}

// validateSSHKey normalizes + validates an operator-pasted OpenSSH public key
// destined for the seed's RASPUTIN_SSH_AUTHORIZED_KEY line. Empty is valid —
// images bake no SSH key at all, so "no key" simply means a console/UI-only
// node. Mirrors resolveSSHKey in cmd/rasputin-provision, same rules for the
// same reason: the line is rendered double-quoted and sourced by sh on the
// node, so a quote/dollar/backslash/backtick would break every seed field.
export function validateSSHKey(input: string): { key: string; error?: string } {
  const key = input.trim();
  if (key === '') return { key: '' };
  if (/[\n\r]/.test(key)) return { key, error: 'paste a single key line (one key only)' };
  if (/["$\\`]/.test(key)) return { key, error: 'the key must not contain ", $, \\ or ` characters' };
  const fields = key.split(/\s+/);
  if (fields.length < 2 || !/^(ssh-|ecdsa-|sk-)/.test(fields[0])) {
    return { key, error: 'that doesn’t look like an SSH public key — expected something like "ssh-ed25519 AAAA… you@laptop"' };
  }
  return { key };
}

// sshKeyLine renders the optional seed line ('' when no key). Double-quoted:
// the seed is sourced by sh and the key value contains spaces.
function sshKeyLine(sshKey: string): string {
  return sshKey ? `RASPUTIN_SSH_AUTHORIZED_KEY="${sshKey}"\n` : '';
}

// renderNodeSeed builds the rasputin-seed.env the new node's firstboot reads.
// Mirrors buildrootSeed (role / node-id / NATS url / join token / ssh key).
export function renderNodeSeed(
  role: AddableRole,
  nodeId: string,
  token: string,
  sshKey: string = '',
  natsUrl: string = DEFAULT_NATS_URL,
): string {
  return (
    `# rasputin-seed.env — node enrollment file (generated by the Rasputin control plane)\n` +
    `RASPUTIN_NODE_ROLE=${role}\n` +
    `RASPUTIN_NODE_ID=${nodeId}\n` +
    `RASPUTIN_NATS_URL=${natsUrl}\n` +
    `RASPUTIN_CP_JOIN_TOKEN=${token}\n` +
    sshKeyLine(sshKey)
  );
}

// renderFirewallSeed builds the firewall's seed.env — the SAME four keys as a
// node seed (role / node-id / NATS url / join token, always with a token), but
// the firewall consumes it differently: it lands at /etc/rasputin/seed.env over
// SSH and is applied by apply-seed, rather than on a boot-partition FAT read by
// firstboot. Mirrors openwrtSeed() in cmd/rasputin-provision so a UI-enrolled
// firewall and a CLI-provisioned one are byte-compatible. See
// firewall-image.md + token-provisioning-pipeline.md.
export function renderFirewallSeed(
  nodeId: string,
  token: string,
  sshKey: string = '',
  natsUrl: string = DEFAULT_NATS_URL,
): string {
  return (
    `# seed.env (firewall) — enrollment file (generated by the Rasputin control plane)\n` +
    `RASPUTIN_NODE_ROLE=firewall\n` +
    `RASPUTIN_NODE_ID=${nodeId}\n` +
    `RASPUTIN_NATS_URL=${natsUrl}\n` +
    `RASPUTIN_CP_JOIN_TOKEN=${token}\n` +
    sshKeyLine(sshKey)
  );
}

// FIREWALL_HOST_PLACEHOLDER is the stand-in the operator replaces with their
// firewall's LAN address in the delivery command. Kept as one constant so the
// hint text and the command can't drift apart.
export const FIREWALL_HOST_PLACEHOLDER = '<firewall-ip>';

// firewallApplyCommand builds the one line the operator runs (from the folder
// holding the downloaded seed.env) to enroll an ALREADY-IMAGED firewall: copy
// the seed into place, then apply it. Unlike a fresh OS node — which is flashed
// blank and self-seeds on first boot — the firewall is already running its own
// image, so enrollment is an over-the-network push, not a re-flash. The `-O`
// forces scp's legacy protocol (the firewall's SSH server doesn't speak the
// newer SFTP-based transfer). apply-seed pushes the seed into config and the
// agent auto-starts.
export function firewallApplyCommand(host: string = FIREWALL_HOST_PLACEHOLDER): string {
  return (
    `scp -O seed.env root@${host}:/etc/rasputin/seed.env && ` +
    `ssh root@${host} /usr/lib/rasputin/apply-seed`
  );
}

// OS_RELEASES_URL is the OS source repo whose public Releases hold the node OS
// images, read directly since the repos went public (ADR-0002). The add-node
// wizard links here so a new node is flashed with the *same* build the cluster
// runs. (Interim: a direct release link. The per-cluster image/storefront
// delivery is a deferred Phase-2 item — token-provisioning-pipeline §6 — and
// would replace this URL.)
const OS_RELEASES_URL = 'https://github.com/geekdojo/rasputin-os';

export interface NodeImage {
  version: string;
  asset: string;
  downloadUrl: string;
  releaseUrl: string;
}

// nodeImageFor builds the public download for the node OS image at a given
// version + architecture — pass the cluster's OS version so a new node matches
// it, and the arch the operator is flashing for. Returns null when the version
// is unknown (the wizard then falls back to generic guidance). The image is
// verifiable against the `imageSha256` in the release's manifest.json.
export function nodeImageFor(
  osVersion: string | undefined | null,
  arch: NodeArch = 'amd64',
): NodeImage | null {
  const v = (osVersion ?? '').trim();
  if (!v) return null;
  // The OS source repo tags bare CalVer (ADR-0002 — no os- mirror prefix).
  const tag = v;
  const asset = `rasputin-os-${skuForArch(arch)}-${v}.img.xz`;
  return {
    version: v,
    asset,
    downloadUrl: `${OS_RELEASES_URL}/releases/download/${tag}/${asset}`,
    releaseUrl: `${OS_RELEASES_URL}/releases/tag/${tag}`,
  };
}

// flashCommand builds the single line the operator pastes on their laptop to
// flash + enroll a new node ("plug in the drive, run this"). The control plane
// serves the secret-free flasher at /flash.sh; the node's seed — the only
// secret — rides along as a base64 env var (never in a URL). The script
// downloads the cluster's image, verifies its checksum, flashes the drive,
// writes the seed AND reads it back to confirm it landed, then ejects. We pin
// the control-plane host to its stable mDNS name so the command is identical
// regardless of how the operator reached this UI (IP vs name). The arch selects
// which image the flasher pulls (RASPUTIN_ARCH → /api/cluster/node-image?arch=);
// it's only added to the line for non-default (arm64) so amd64 commands are
// unchanged.
export function flashCommand(seed: string, arch: NodeArch = 'amd64', cpBase = 'https://rasputin.local'): string {
  const archEnv = arch !== 'amd64' ? `RASPUTIN_ARCH=${arch} ` : '';
  // Base64 the seed UTF-8-safely. btoa() throws on any char outside Latin1, and
  // the seed's comment line carries an em dash (and a node name could hold other
  // non-ASCII) — so encode to UTF-8 bytes first, then base64 those. flash.sh's
  // `base64 -d` reproduces the exact bytes.
  if (typeof btoa === 'function') {
    const bytes = new TextEncoder().encode(seed);
    let bin = '';
    for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
    return `curl -fsSL ${cpBase}/flash.sh | sudo ${archEnv}RASPUTIN_SEED_B64='${btoa(bin)}' bash`;
  }
  // SSR/test fallback; the browser path uses btoa.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const b64 = (globalThis as any).Buffer.from(seed, 'utf8').toString('base64');
  return `curl -fsSL ${cpBase}/flash.sh | sudo ${archEnv}RASPUTIN_SEED_B64='${b64}' bash`;
}

// clusterPrefixOf derives the "<cluster>-" id prefix every node shares, from the
// existing inventory: the longest common prefix, trimmed back to the last '-'.
// Returns '' when there's no shared dash-delimited prefix (then suggestions are
// bare "<role><n>", which the user can edit).
export function clusterPrefixOf(ids: string[]): string {
  if (ids.length === 0) return '';
  let lcp = ids[0];
  for (let k = 1; k < ids.length; k++) {
    const id = ids[k];
    let i = 0;
    while (i < lcp.length && i < id.length && lcp[i] === id[i]) i++;
    lcp = lcp.slice(0, i);
    if (lcp === '') break;
  }
  const cut = lcp.lastIndexOf('-');
  return cut >= 0 ? lcp.slice(0, cut + 1) : '';
}

// suggestNodeId proposes the next free "<prefix><role><n>" id, matching the
// rasputin-provision auto-naming convention and skipping any id already taken
// (live nodes or pending enrollments).
export function suggestNodeId(prefix: string, role: AddableRole, taken: Set<string>): string {
  const re = new RegExp(`^${escapeRe(prefix + role)}(\\d+)$`);
  let max = 0;
  for (const id of taken) {
    const m = id.match(re);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  let n = max + 1;
  let candidate = `${prefix}${role}${n}`;
  while (taken.has(candidate)) candidate = `${prefix}${role}${++n}`;
  return candidate;
}

// downloadSeed triggers a browser download of the enrollment file. The default
// filename `rasputin-seed.env` is what an OS node's firstboot expects on the
// boot partition, so the user can drop it straight on without renaming; the
// firewall path passes `seed.env` (the name apply-seed / the scp command
// expect).
export function downloadSeed(contents: string, filename: string = 'rasputin-seed.env'): void {
  const blob = new Blob([contents], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
