// Node-enrollment helpers for the "Add node" flow. The seed renderer mirrors
// buildrootSeed() in cmd/rasputin-provision so a UI-minted node and a
// CLI-provisioned node consume byte-compatible enrollment files — the firstboot
// oneshot parses the same KEY=VALUE lines either way.

// The locked control-plane name. Agents resolve it via mDNS, so the seed never
// carries an IP (avoids the F-LOG-1 churn — see token-provisioning-pipeline.md).
export const DEFAULT_NATS_URL = 'nats://rasputin.local:4222';

// Roles a user can add from the UI. The controlplane self-registers and the
// firewall is provisioned with the cluster, so neither is an "add a node" path.
export type AddableRole = 'compute' | 'storage';

// renderNodeSeed builds the rasputin-seed.env the new node's firstboot reads.
// Mirrors buildrootSeed (role / node-id / NATS url / join token).
export function renderNodeSeed(
  role: AddableRole,
  nodeId: string,
  token: string,
  natsUrl: string = DEFAULT_NATS_URL,
): string {
  return (
    `# rasputin-seed.env — node enrollment file (generated by the Rasputin control plane)\n` +
    `RASPUTIN_NODE_ROLE=${role}\n` +
    `RASPUTIN_NODE_ID=${nodeId}\n` +
    `RASPUTIN_NATS_URL=${natsUrl}\n` +
    `RASPUTIN_CP_JOIN_TOKEN=${token}\n`
  );
}

// RELEASES_CHANNEL_URL is the public release channel the node OS images are
// published to. The add-node wizard links here so a new node is flashed with
// the *same* build the cluster runs. (Interim: a direct release link. The
// per-cluster image/storefront delivery is a deferred Phase-2 item —
// token-provisioning-pipeline §6 — and would replace this URL.)
const RELEASES_CHANNEL_URL = 'https://github.com/geekdojo/rasputin-releases';

export interface NodeImage {
  version: string;
  asset: string;
  downloadUrl: string;
  releaseUrl: string;
}

// nodeImageFor builds the public download for the n100 node OS image at a given
// version — pass the cluster's OS version so a new node matches it. SKU is n100
// (the only v1 SKU). Returns null when the version is unknown (the wizard then
// falls back to generic guidance). The image is verifiable against the
// `imageSha256` in the release's manifest.json.
export function nodeImageFor(osVersion: string | undefined | null): NodeImage | null {
  const v = (osVersion ?? '').trim();
  if (!v) return null;
  const tag = `os-${v}`;
  const asset = `rasputin-os-n100-${v}.img.xz`;
  return {
    version: v,
    asset,
    downloadUrl: `${RELEASES_CHANNEL_URL}/releases/download/${tag}/${asset}`,
    releaseUrl: `${RELEASES_CHANNEL_URL}/releases/tag/${tag}`,
  };
}

// flashCommand builds the single line the operator pastes on their laptop to
// flash + enroll a new node ("plug in the drive, run this"). The control plane
// serves the secret-free flasher at /flash.sh; the node's seed — the only
// secret — rides along as a base64 env var (never in a URL). The script
// downloads the cluster's image, verifies its checksum, flashes the drive,
// writes the seed AND reads it back to confirm it landed, then ejects. We pin
// the control-plane host to its stable mDNS name so the command is identical
// regardless of how the operator reached this UI (IP vs name).
export function flashCommand(seed: string, cpBase = 'https://rasputin.local'): string {
  // Base64 the seed UTF-8-safely. btoa() throws on any char outside Latin1, and
  // the seed's comment line carries an em dash (and a node name could hold other
  // non-ASCII) — so encode to UTF-8 bytes first, then base64 those. flash.sh's
  // `base64 -d` reproduces the exact bytes.
  if (typeof btoa === 'function') {
    const bytes = new TextEncoder().encode(seed);
    let bin = '';
    for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
    return `curl -fsSL ${cpBase}/flash.sh | sudo RASPUTIN_SEED_B64='${btoa(bin)}' bash`;
  }
  // SSR/test fallback; the browser path uses btoa.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const b64 = (globalThis as any).Buffer.from(seed, 'utf8').toString('base64');
  return `curl -fsSL ${cpBase}/flash.sh | sudo RASPUTIN_SEED_B64='${b64}' bash`;
}

// clusterPrefixOf derives the "<cluster>-" id prefix every node shares, from the
// existing inventory: the longest common prefix, trimmed back to the last '-'.
// Returns '' when there's no shared dash-delimited prefix (then suggestions are
// bare "<role><n>", which the user can edit).
export function clusterPrefixOf(ids: string[]): string {
  if (ids.length === 0) return '';
  let lcp = ids[0];
  for (let k = 1; k < ids.length; k++) {
    const id = ids[k];
    let i = 0;
    while (i < lcp.length && i < id.length && lcp[i] === id[i]) i++;
    lcp = lcp.slice(0, i);
    if (lcp === '') break;
  }
  const cut = lcp.lastIndexOf('-');
  return cut >= 0 ? lcp.slice(0, cut + 1) : '';
}

// suggestNodeId proposes the next free "<prefix><role><n>" id, matching the
// rasputin-provision auto-naming convention and skipping any id already taken
// (live nodes or pending enrollments).
export function suggestNodeId(prefix: string, role: AddableRole, taken: Set<string>): string {
  const re = new RegExp(`^${escapeRe(prefix + role)}(\\d+)$`);
  let max = 0;
  for (const id of taken) {
    const m = id.match(re);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  let n = max + 1;
  let candidate = `${prefix}${role}${n}`;
  while (taken.has(candidate)) candidate = `${prefix}${role}${++n}`;
  return candidate;
}

// downloadSeed triggers a browser download of the enrollment file as
// rasputin-seed.env — the exact filename firstboot expects on the boot
// partition, so the user can drop it straight on without renaming.
export function downloadSeed(contents: string): void {
  const blob = new Blob([contents], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'rasputin-seed.env';
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
