// Node-enrollment helpers for the "Add node" flow. The seed renderer mirrors
// buildrootSeed() in cmd/rasputin-provision so a UI-minted node and a
// CLI-provisioned node consume byte-compatible enrollment files — the firstboot
// oneshot parses the same KEY=VALUE lines either way.

// The locked control-plane name. Agents resolve it via mDNS, so the seed never
// carries an IP (avoids the F-LOG-1 churn — see token-provisioning-pipeline.md).
export const DEFAULT_NATS_URL = 'nats://rasputin.local:4222';

// Roles a user can add from the UI. The controlplane self-registers and the
// firewall is provisioned with the cluster, so neither is an "add a node" path.
export type AddableRole = 'compute' | 'storage';

// renderNodeSeed builds the rasputin-seed.env the new node's firstboot reads.
// Mirrors buildrootSeed (role / node-id / NATS url / join token).
export function renderNodeSeed(
  role: AddableRole,
  nodeId: string,
  token: string,
  natsUrl: string = DEFAULT_NATS_URL,
): string {
  return (
    `# rasputin-seed.env — node enrollment file (generated by the Rasputin control plane)\n` +
    `RASPUTIN_NODE_ROLE=${role}\n` +
    `RASPUTIN_NODE_ID=${nodeId}\n` +
    `RASPUTIN_NATS_URL=${natsUrl}\n` +
    `RASPUTIN_CP_JOIN_TOKEN=${token}\n`
  );
}

// clusterPrefixOf derives the "<cluster>-" id prefix every node shares, from the
// existing inventory: the longest common prefix, trimmed back to the last '-'.
// Returns '' when there's no shared dash-delimited prefix (then suggestions are
// bare "<role><n>", which the user can edit).
export function clusterPrefixOf(ids: string[]): string {
  if (ids.length === 0) return '';
  let lcp = ids[0];
  for (let k = 1; k < ids.length; k++) {
    const id = ids[k];
    let i = 0;
    while (i < lcp.length && i < id.length && lcp[i] === id[i]) i++;
    lcp = lcp.slice(0, i);
    if (lcp === '') break;
  }
  const cut = lcp.lastIndexOf('-');
  return cut >= 0 ? lcp.slice(0, cut + 1) : '';
}

// suggestNodeId proposes the next free "<prefix><role><n>" id, matching the
// rasputin-provision auto-naming convention and skipping any id already taken
// (live nodes or pending enrollments).
export function suggestNodeId(prefix: string, role: AddableRole, taken: Set<string>): string {
  const re = new RegExp(`^${escapeRe(prefix + role)}(\\d+)$`);
  let max = 0;
  for (const id of taken) {
    const m = id.match(re);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  let n = max + 1;
  let candidate = `${prefix}${role}${n}`;
  while (taken.has(candidate)) candidate = `${prefix}${role}${++n}`;
  return candidate;
}

// downloadSeed triggers a browser download of the enrollment file as
// rasputin-seed.env — the exact filename firstboot expects on the boot
// partition, so the user can drop it straight on without renaming.
export function downloadSeed(contents: string): void {
  const blob = new Blob([contents], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'rasputin-seed.env';
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
