#!/usr/bin/env bash
# gen-app-secret-vectors.sh — regenerate the frozen derivation vectors at
# api/internal/appsecret/testdata/derivation-vectors.json WITHOUT calling the Go
# code they pin.
#
# Why this script exists. api/internal/console/sha512crypt_test.go states the
# rule: hand-rolled spec code is checked against OTHER implementations, never
# against itself. A vectors file generated by the implementation under test
# pins nothing — it passes for any derivation, including a wrong one, and goes
# on passing after a refactor silently changes the output. ADR-0006 Decision 11a
# makes that a fleet-wide break on upgrade rather than a test failure: every
# deployed app would be handed a credential it never received while its data
# volume still held the old one.
#
# So every value below is produced TWICE, by two implementations that share no
# code with the Go package and none with each other:
#
#   1. OpenSSL's HKDF (openssl kdf -kdfopt mode:EXPAND_ONLY), i.e. the C
#      implementation in libcrypto.
#   2. A Python HKDF-Expand written here straight from RFC 5869 §2.3, using
#      nothing but hmac/hashlib — and checked, before it is used for anything,
#      against RFC 5869's own published test vectors (Appendix A.1-A.3). That
#      check is what makes this half a reading of the SPEC rather than a second
#      guess at it.
#
# The two must agree byte for byte or this script refuses to write. The Go test
# (derivation_vectors_test.go) then loads the file and compares — a third
# implementation, and the one that is allowed to be wrong.
#
# The `info` encoding is emitted alongside each value as infoHex, so the Go test
# pins the length-prefixed structure independently of the KDF: a vector file
# that only carried outputs could not tell a changed info encoding from a
# changed hash.
#
# Regenerate only when ADDING cases. If a change to the derivation makes an
# existing case's value move, that is the freeze being broken — add a
# derivationVersion, do not re-bless the file.

set -euo pipefail
cd "$(dirname "$0")/.."
out=api/internal/appsecret/testdata/derivation-vectors.json

command -v openssl >/dev/null || { echo "openssl not found (needs OpenSSL 3.x for 'openssl kdf')" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 not found" >&2; exit 1; }

openssl_version="$(openssl version)"
python_version="$(python3 -c 'import sys; print("Python "+sys.version.split()[0])')"

OPENSSL_VERSION="$openssl_version" PYTHON_VERSION="$python_version" OUT="$out" python3 - <<'PY'
import hashlib, hmac, json, os, struct, subprocess, sys
from base64 import urlsafe_b64encode

# --- implementation 2: RFC 5869 §2.3, from the text. ------------------------

def hkdf_expand(prk: bytes, info: bytes, length: int) -> bytes:
    hash_len = hashlib.sha256().digest_size
    n = -(-length // hash_len)
    if n > 255:
        raise ValueError("length too large for HKDF")
    okm, t = b"", b""
    for i in range(1, n + 1):
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        okm += t
    return okm[:length]

def hkdf_extract(salt: bytes, ikm: bytes) -> bytes:
    return hmac.new(salt, ikm, hashlib.sha256).digest()

# RFC 5869 Appendix A, the SHA-256 cases. Checked before this implementation is
# trusted to generate anything: a generator nobody validated is just a third
# opinion.
RFC5869 = [
    dict(ikm="0b"*22, salt="000102030405060708090a0b0c", info="f0f1f2f3f4f5f6f7f8f9", L=42,
         okm="3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865"),
    dict(ikm="".join("%02x" % i for i in range(0x50)),
         salt="".join("%02x" % i for i in range(0x60, 0xb0)),
         info="".join("%02x" % i for i in range(0xb0, 0x100)), L=82,
         okm="b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71cc30c58179ec3e87c14c01d5c1f3434f1d87"),
    dict(ikm="0b"*22, salt="", info="", L=42,
         okm="8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8"),
]
for i, v in enumerate(RFC5869, 1):
    prk = hkdf_extract(bytes.fromhex(v["salt"]) or b"\0" * 32, bytes.fromhex(v["ikm"]))
    got = hkdf_expand(prk, bytes.fromhex(v["info"]), v["L"]).hex()
    if got != v["okm"]:
        sys.exit(f"the Python HKDF fails RFC 5869 Appendix A.{i} — refusing to generate vectors with it")

# --- implementation 1: OpenSSL's libcrypto. ---------------------------------

def openssl_expand(prk: bytes, info: bytes, length: int) -> bytes:
    cmd = ["openssl", "kdf", "-keylen", str(length),
           "-kdfopt", "mode:EXPAND_ONLY", "-kdfopt", "digest:SHA256",
           "-kdfopt", "hexkey:" + prk.hex(),
           "-kdfopt", "hexinfo:" + (info.hex() if info else ""),
           "-binary", "HKDF"]
    return subprocess.run(cmd, check=True, capture_output=True).stdout

# --- the derivation under test, version 1. ---------------------------------

SECRET_LEN = 32

def info_v1(app_id: str, name: str, version: int) -> bytes:
    a, n = app_id.encode(), name.encode()
    return struct.pack(">I", len(a)) + a + struct.pack(">I", len(n)) + n + struct.pack(">I", version)

def b64url_nopad(b: bytes) -> str:
    return urlsafe_b64encode(b).decode().rstrip("=")

# --- the cases. -------------------------------------------------------------
#
# Each one pins something a re-implementation could get wrong. The two
# length-prefix cases are the pair that a separator-joined info string would
# collapse: "a" + "bc" and "ab" + "c" are the same bytes once a separator is
# removed, and they must not be the same secret.
CASES = [
    dict(why="all-zero seed, a real ULID appID, the first rotation — the plainest case, and the one a re-implementation gets right first",
         seed="00" * 32, appId="01K5R6P8Q9ZJ7V2XW4YB3D5EFG", name="db-password", version=1),
    dict(why="all-0xff seed: the seed is used as the HKDF PRK verbatim, so a high-bit-set key is not special-cased anywhere",
         seed="ff" * 32, appId="01K5R6P8Q9ZJ7V2XW4YB3D5EFG", name="db-password", version=1),
    dict(why="a fixed pseudo-random seed, so the vectors do not all sit on a degenerate key",
         seed="6f4e2a1b8c3d5e7f90a1b2c3d4e5f60718293a4b5c6d7e8f9012345678abcdef",
         appId="01K5R6P8Q9ZJ7V2XW4YB3D5EFG", name="session-key", version=1),
    dict(why="rotation version 2: the version is part of the tuple, so the same (seed, appID, name) at n+1 is a different value",
         seed="6f4e2a1b8c3d5e7f90a1b2c3d4e5f60718293a4b5c6d7e8f9012345678abcdef",
         appId="01K5R6P8Q9ZJ7V2XW4YB3D5EFG", name="session-key", version=2),
    dict(why="version 0xffffffff pins the uint32 BIG-endian encoding of the version; a little-endian writer produces a different value here and an identical one at version 1 only by luck",
         seed="6f4e2a1b8c3d5e7f90a1b2c3d4e5f60718293a4b5c6d7e8f9012345678abcdef",
         appId="01K5R6P8Q9ZJ7V2XW4YB3D5EFG", name="session-key", version=4294967295),
    dict(why="length-prefix injectivity, half one: appID 'a', name 'bc'",
         seed="00" * 32, appId="a", name="bc", version=1),
    dict(why="length-prefix injectivity, half two: appID 'ab', name 'c' — concatenation without lengths makes this the same input as half one, and length prefixing is what stops an author-supplied name reaching another app's tuple",
         seed="00" * 32, appId="ab", name="c", version=1),
    dict(why="a 63-character name, the longest a DNS-1123 label allows, so the name's own length prefix is exercised at its bound",
         seed="00" * 32, appId="01K5R6P8Q9ZJ7V2XW4YB3D5EFG",
         name="a" + "b" * 61 + "c", version=1),
    dict(why="a one-character name and a one-character appID: the shortest legal tuple",
         seed="00" * 32, appId="z", name="k", version=1),
]

vectors = []
for c in CASES:
    seed = bytes.fromhex(c["seed"])
    if len(seed) != 32:
        sys.exit("a seed in this file is not 32 bytes")
    info = info_v1(c["appId"], c["name"], c["version"])
    a = openssl_expand(seed, info, SECRET_LEN)
    b = hkdf_expand(seed, info, SECRET_LEN)
    if a != b:
        sys.exit(f"OpenSSL and the RFC 5869 reading disagree on {c!r} — refusing to write vectors")
    vectors.append(dict(why=c["why"], seedHex=c["seed"], appId=c["appId"], name=c["name"],
                        version=c["version"], infoHex=info.hex(), want=b64url_nopad(a)))

values = [v["want"] for v in vectors]
if len(set(values)) != len(values):
    sys.exit("two cases derived the same value — a vector set that cannot distinguish tuples pins nothing")

doc = {
    "comment": ("FROZEN derivation vectors for ADR-0006 Decision 11a (geekdojo/geekdojo-brain#520). "
                "Generated by scripts/gen-app-secret-vectors.sh from TWO implementations that share no code with "
                "api/internal/appsecret — OpenSSL's HKDF and an RFC 5869 reading in Python checked against the RFC's "
                "own Appendix A vectors — which agreed byte for byte. If a code change makes a case here fail, the "
                "frozen derivation has changed: add a derivationVersion, do NOT regenerate this file."),
    "derivationVersion": 1,
    "algorithm": "HKDF-Expand-SHA256(seed, info, 32)",
    "info": "uint32be(len(appID)) || appID || uint32be(len(name)) || name || uint32be(version)",
    "encoding": "base64url, no padding",
    "generatedBy": [os.environ["OPENSSL_VERSION"], os.environ["PYTHON_VERSION"]],
    "cases": vectors,
}
with open(os.environ["OUT"], "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
print(f"wrote {os.environ['OUT']} ({len(vectors)} cases), agreed by:")
print(f"  {os.environ['OPENSSL_VERSION']}")
print(f"  {os.environ['PYTHON_VERSION']} (RFC 5869 §2.3, validated against Appendix A.1-A.3)")
PY
