// Package appsecret implements the ${secret:<name>} channel — the one way a
// catalog tile says "I need a generated credential here" (ADR-0006 Decision
// 11a, geekdojo/geekdojo-brain#520).
//
// # Why it exists
//
// Three shipped tiles — karakeep, romm, immich — carry hardcoded credentials in
// a PUBLIC repository, so the session-signing key and database password of
// every cluster running them is known to anyone who reads the catalog. That is
// finding F29 of the auth threat model, rated high. It is not three authors
// being careless: a catalog compose is a static file and the control plane
// refuses to edit it, so until this package there was nowhere for a tile to put
// a generated value. The shipped pi-hole tile hardcoding `changeme` as the
// admin password on a DNS server is the same absence, and so is Linkding being
// rejected from the catalog for needing a value it does in fact support.
//
// # Derived, never stored
//
// A value is a pure function of (seed, appID, name, version). Nothing is
// persisted per secret, and that is not a space optimisation — it is what buys
// the two properties the design is chosen for:
//
//   - Moving an app between nodes is a non-event. An appID does not change when
//     an app is rescheduled, so the value re-derives byte-identical on the new
//     node. A stored secret makes every reschedule a data-movement problem with
//     its own way to fail.
//   - No new class of secret at rest. One seed file at 0600 in the existing
//     trustDir beside the mesh CA's private key, on the dedicated
//     /var/lib/rasputin partition — so it survives A/B image switches and
//     rollbacks by the same construction the mesh already relies on.
//
// # The derivation is FROZEN
//
// Algorithm, info encoding, output length and output encoding freeze the moment
// the first secret is minted on a customer cluster. Changing any of them in a
// later control-plane release hands every deployed app a credential it never
// received while its data volume still holds the old one: the app does not
// fail over, it fails to authenticate against its own database, on every
// cluster, at the same moment. A fleet-wide break on upgrade, not a rolling
// failure.
//
// Two mechanisms hold it. A DerivationVersion is persisted beside the seed and
// dispatched on, so a change is a NEW version that old seeds never select
// rather than an edit to the one they do. And committed golden vectors
// (testdata/derivation-vectors.json) pin version 1 byte for byte, generated by
// implementations other than this one — see the vectors test for why that
// matters.
//
// # Substitution happens on the way OUT to a node
//
// Never into the database. The control plane's SQLite is opened through plain
// modernc.org/sqlite with no encryption at rest, so resolving in the install
// handler would write plaintext credentials into apps.compose_yaml permanently,
// and the UI's compose preview would show a live credential instead of a
// placeholder. Resolve is called where the compose is marshalled into
// proto.AppDeployCmd and nowhere else; the two other node-bound paths escape
// the token instead (see Escape).
package appsecret

import (
	"crypto/hkdf"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/geekdojo/rasputin-control-plane/tileschema"
)

const (
	// DerivationVersion is the derivation this build MINTS a new seed under.
	// It is not the only one this build can derive with: a seed file written by
	// an older release carries its own, and Seed.Derive dispatches on that.
	DerivationVersion = 1

	// SeedLen is the seed's length in bytes. 32 is the SHA-256 output size,
	// which is what HKDF-Expand requires of a pseudorandom key it is handed
	// directly.
	SeedLen = 32

	// InitialVersion is the rotation counter a secret starts at. ADR-0006
	// Decision 11a: rotation moves the version field of the derivation tuple,
	// and what is stored per app is n — a small non-sensitive integer — never
	// the secret. Storing n, and the API that increments it, is not this issue:
	// every caller here passes InitialVersion, and the parameter exists so that
	// adding the counter later is a plumbing change and not a change to a
	// frozen derivation.
	InitialVersion uint32 = 1

	// maxAppIDLen bounds the appID that reaches the derivation. An appID is a
	// ULID (26 chars) for every app the catalog installs, and a custom app's is
	// minted by the api, so this is slack rather than a limit anyone meets.
	//
	// It is here because the info string length-prefixes with uint32 and Go
	// would silently truncate a longer one on the conversion — which is the one
	// way the length prefixing could stop being injective and so the one way
	// the property this whole encoding exists for could be lost quietly.
	maxAppIDLen = 256
)

// Seed is one installation's app-secret seed together with the derivation
// version the seed file was written under.
//
// The version travels WITH the key rather than being read from a global,
// because the pair is what identifies a derivation: a build that understands
// two versions must derive under the one its seed was minted with, forever, not
// the newest one it knows.
type Seed struct {
	key               []byte
	derivationVersion int
}

// NewSeed wraps a raw seed and the derivation version it was minted under.
//
// It refuses a version this build cannot derive with rather than falling back
// to one it can. A newer control plane wrote that file, and guessing would mint
// credentials under the wrong derivation — silently, and for as long as nobody
// noticed the apps could no longer authenticate.
func NewSeed(key []byte, derivationVersion int) (*Seed, error) {
	if len(key) != SeedLen {
		return nil, fmt.Errorf("appsecret: seed is %d bytes, want %d", len(key), SeedLen)
	}
	if !supportedDerivation(derivationVersion) {
		return nil, fmt.Errorf("appsecret: seed declares derivation version %d, which this build cannot derive with (it knows %d) — a newer release wrote it, and deriving under a version this seed was not minted with would hand every app a credential it never received",
			derivationVersion, DerivationVersion)
	}
	return &Seed{key: slices.Clone(key), derivationVersion: derivationVersion}, nil
}

// DerivationVersion is the version this seed derives under, for the record a
// log line or a status page shows.
func (s *Seed) DerivationVersion() int {
	if s == nil {
		return 0
	}
	return s.derivationVersion
}

func supportedDerivation(v int) bool { return v == 1 }

// Derive returns the secret value for (appID, name, version) under this seed.
//
// A nil receiver is an error rather than a zero value: the paths that call this
// have a real app and a real container waiting for a real credential, and an
// empty string would be deployed as a password.
func (s *Seed) Derive(appID, name string, version uint32) (string, error) {
	if s == nil {
		return "", errors.New("appsecret: no app-secret seed is loaded, so ${secret:} cannot be resolved")
	}
	if strings.TrimSpace(appID) == "" {
		return "", errors.New("appsecret: refusing to derive for an empty appID: the appID is what separates one app's secrets from another's")
	}
	if len(appID) > maxAppIDLen {
		return "", fmt.Errorf("appsecret: appID is %d bytes, over the %d-byte bound the length-prefixed info string can encode without truncating", len(appID), maxAppIDLen)
	}
	// The same guard the publisher and the catalog loader already ran
	// (tileschema.ScanSecretTokens). Run again here because this is the last
	// point before author-supplied text becomes part of a key derivation, and
	// because a custom app's compose reaches this path without ever having been
	// a tile.
	if !tileschema.ValidSecretName(name) {
		return "", fmt.Errorf("appsecret: secret name %q is not a DNS-1123 label", name)
	}

	switch s.derivationVersion {
	case 1:
		return deriveV1(s.key, appID, name, version)
	default:
		// Unreachable while NewSeed is the only constructor; kept so that
		// adding version 2 is a new case and never an edit to version 1.
		return "", fmt.Errorf("appsecret: no derivation for version %d", s.derivationVersion)
	}
}

// --- DERIVATION VERSION 1. FROZEN. DO NOT EDIT ANY BYTE OF WHAT FOLLOWS. ---
//
//	value = base64url-nopad( HKDF-Expand-SHA256(seed, info, 32) )
//	info  = uint32be(len(appID)) || appID || uint32be(len(name)) || name || uint32be(version)
//
// A change here is not a refactor, it is a fleet-wide credential break on
// upgrade (see the package comment). Change it by adding deriveV2 and a case
// above, which existing seeds never select.

// secretLenV1 is the derived secret's length in bytes before encoding. 32 is
// the SHA-256 output size and 256 bits of entropy, which is more than any
// consumer in the corpus needs and cheap enough that no tile ever needs to ask
// for a different length — a per-secret length would be a second frozen
// parameter for no gain.
const secretLenV1 = 32

// deriveV1 is derivation version 1.
//
// HKDF-Expand, not the full Extract-then-Expand: the seed is already 32 bytes
// of CSPRNG output, so it is a uniformly random key and there is no
// non-uniformity for Extract to condition away. Expand alone is what RFC 5869
// §3.3 describes for exactly this case, and it is the construction the frozen
// vectors pin.
func deriveV1(seed []byte, appID, name string, version uint32) (string, error) {
	out, err := hkdf.Expand(sha256.New, seed, string(infoV1(appID, name, version)), secretLenV1)
	if err != nil {
		return "", fmt.Errorf("appsecret: hkdf expand: %w", err)
	}
	// base64url WITHOUT padding, chosen for where the value lands: a compose
	// env var, read by docker compose's own interpolator. The standard
	// alphabet's `+` and `/` and base64's `=` padding are all characters that
	// have to be quoted or escaped somewhere in that chain; base64url-nopad has
	// none of them, so the value is safe unquoted in YAML, in an env file, and
	// in a shell the app's entrypoint might pass it through. Frozen with
	// everything else: the ENCODED string is the credential the app stores, so
	// re-encoding the same bytes differently is the same break as deriving
	// different bytes.
	return base64.RawURLEncoding.EncodeToString(out), nil
}

// infoV1 builds the HKDF info string for version 1.
//
// LENGTH-PREFIXED, never concatenated with a separator. A separator is
// injective only while no component can contain it: appIDs are ULIDs and
// cannot, but `name` is AUTHOR-SUPPLIED, so with (say) ":" as the separator a
// tile could name its secret `x:<other-app-id>:y` and derive a second app's
// secret from its own tuple. Length prefixing removes that by construction
// rather than by relying on the name validator to stay as strict as it is
// today — defence that does not depend on another file's rules is the only kind
// worth freezing.
//
// Every prefix, and the version, is uint32 BIG-endian. Big-endian because it is
// the network byte order every other length on the wire in this tree uses, and
// fixed-width because a varint's encoding is one more thing that could be
// implemented differently by the independent generator that pins these vectors.
func infoV1(appID, name string, version uint32) []byte {
	info := make([]byte, 0, 4+len(appID)+4+len(name)+4)
	info = binary.BigEndian.AppendUint32(info, uint32(len(appID)))
	info = append(info, appID...)
	info = binary.BigEndian.AppendUint32(info, uint32(len(name)))
	info = append(info, name...)
	info = binary.BigEndian.AppendUint32(info, version)
	return info
}
